name: KOL
author: MyNET
description: 
version: 1.0.0
main: KOL\Main
api: [1.13.0]

commands:
   kingofladder:
     description: KOL
     permission: kol
permissions:
   kol:
     description: 
     default: op
