name: OneOne
author: MyNET
description: Simple 1v1 Plugin
version: 1.0.0_BETA
main: MyNET\OneOne
api: [1.12.0]

commands:
    1v1:
	    permission: 1v1
        description: none
permissions:
    1v1:
        description: none
        default: true
